name: MX4300 NSS Build

on: workflow_dispatch

jobs:
    build:
        name: MX4300 NSS Build
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Install packages
              run: |
                  sudo apt-get update && \
                  sudo apt install -y build-essential \
                  clang \
                  flex \
                  bison \
                  g++ \
                  gawk \
                  gcc-multilib \
                  g++-multilib \
                  gettext \
                  git \
                  libncurses5-dev \
                  libssl-dev \
                  python3-setuptools \
                  rsync \
                  swig \
                  unzip \
                  zlib1g-dev \
                  file \
                  wget && \
                  sudo apt-get clean

            - name: Checkout
              uses: actions/checkout@v4

            - name: Update scripts
              run:  ./scripts/feeds update

            - name: Install scripts
              run:  ./scripts/feeds install -a

            - name: Generate config
              run:  cp nss-setup/config-nss.seed .config

            - name: Generate config pt 2
              run:  make defconfig V=s -j4

            - name: Build firmware images
              run: make -j$(($(nproc)+1))

            - name: Pack packages
              run:  tar cvfz bin/packages.tar.gz -C bin/targets/qualcommax/ipq807x/packages .

            - name: Get SHA
              uses: benjlevesque/short-sha@v2.2

            - name: Release
              uses: ncipollo/release-action@v1
              with:
                tag: qualcommax-nss-${{ env.SHA }}
                artifacts: bin/targets/qualcommax/ipq807x/openwrt-qualcommax-ipq807x-*, bin/packages.tar.gz
